[2025-10-07T22:20:04.505+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-07T22:20:05.226+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: name_stream_dag.stream_to_kafka_task scheduled__2025-10-07T21:15:00+00:00 [queued]>
[2025-10-07T22:20:05.298+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: name_stream_dag.stream_to_kafka_task scheduled__2025-10-07T21:15:00+00:00 [queued]>
[2025-10-07T22:20:05.300+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-07T22:20:05.542+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_to_kafka_task> on 2025-10-07 21:15:00+00:00
[2025-10-07T22:20:05.616+0100] {standard_task_runner.py:64} INFO - Started process 1187 to run task
[2025-10-07T22:20:05.637+0100] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'name_stream_dag', 'stream_to_kafka_task', 'scheduled__2025-10-07T21:15:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream_dag.py', '--cfg-path', '/tmp/tmpq99ozawq']
[2025-10-07T22:20:05.662+0100] {standard_task_runner.py:91} INFO - Job 12: Subtask stream_to_kafka_task
[2025-10-07T22:20:06.539+0100] {task_command.py:426} INFO - Running <TaskInstance: name_stream_dag.stream_to_kafka_task scheduled__2025-10-07T21:15:00+00:00 [running]> on host e9a80c19b29d
[2025-10-07T22:20:07.910+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='name_stream_dag' AIRFLOW_CTX_TASK_ID='stream_to_kafka_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T21:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-07T21:15:00+00:00'
[2025-10-07T22:20:07.912+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-07T22:20:18.752+0100] {logging_mixin.py:188} INFO - Delivered to names_topic [0] @ offset 120
[2025-10-07T22:20:29.054+0100] {logging_mixin.py:188} INFO - Delivered to names_topic [0] @ offset 121
[2025-10-07T22:20:33.003+0100] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-10-07T22:20:33.013+0100] {process_utils.py:132} INFO - Sending 15 to group 1187. PIDs of all processes in the group: [1187]
[2025-10-07T22:20:33.028+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 1187
[2025-10-07T22:20:33.029+0100] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-07T22:20:33.048+0100] {logging_mixin.py:188} INFO - Delivered to names_topic [0] @ offset 122
[2025-10-07T22:20:33.049+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-07T22:20:33.211+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream_dag.py", line 29, in _trigger_stream
    initiate_stream()
  File "/opt/airflow/dags/producer/kafka_streaming_service.py", line 223, in initiate_stream
    time.sleep(PAUSE_INTERVAL)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-10-07T22:20:33.295+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=name_stream_dag, task_id=stream_to_kafka_task, run_id=scheduled__2025-10-07T21:15:00+00:00, execution_date=20251007T211500, start_date=20251007T212005, end_date=20251007T212033
[2025-10-07T22:20:33.564+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=1187, status='terminated', exitcode=2, started='22:20:04') (1187) terminated with exit code 2
[2025-10-07T22:20:33.566+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2025-10-07T22:20:33.695+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-07T22:20:37.792+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
